network_seed: 24208
grid_dimension: 6
junctions_to_remove: 2
block_size_m: 280
lane_count: realistic
step_length: 1.0
land_use_block_size_m: 25.0
attractiveness: land_use
traffic_light_strategy: partial_opposites
