network_seed: 42
grid_dimension: 3
junctions_to_remove: 0
block_size_m: 200
lane_count: realistic
step_length: 1.0
land_use_block_size_m: 25.0
attractiveness: land_use
traffic_light_strategy: partial_opposites
