scenarios:
  - name: "original_training_env0"
    num_vehicles: 22000
    private_traffic_seed: 72632
    public_traffic_seed: 27031
    routing_strategy: "realtime 100"
    vehicle_types: "passenger 100"
    passenger_routes: "in 0 out 0 inner 100 pass 0"
    departure_pattern: uniform
    start_time_hour: 8.0

  - name: "original_training_env1"
    num_vehicles: 22000
    private_traffic_seed: 72632
    public_traffic_seed: 27031
    routing_strategy: "realtime 100"
    vehicle_types: "passenger 100"
    passenger_routes: "in 0 out 0 inner 100 pass 0"
    departure_pattern: uniform
    start_time_hour: 8.0

  - name: "original_training_env2"
    num_vehicles: 22000
    private_traffic_seed: 72632
    public_traffic_seed: 27031
    routing_strategy: "realtime 100"
    vehicle_types: "passenger 100"
    passenger_routes: "in 0 out 0 inner 100 pass 0"
    departure_pattern: uniform
    start_time_hour: 8.0

  - name: "original_training_env3"
    num_vehicles: 22000
    private_traffic_seed: 72632
    public_traffic_seed: 27031
    routing_strategy: "realtime 100"
    vehicle_types: "passenger 100"
    passenger_routes: "in 0 out 0 inner 100 pass 0"
    departure_pattern: uniform
    start_time_hour: 8.0
