scenarios:
  - name: "test_env_1"
    num_vehicles: 300
    private_traffic_seed: 100
    public_traffic_seed: 200
    routing_strategy: "realtime 100"
    vehicle_types: "passenger 100"
    passenger_routes: "in 0 out 0 inner 100 pass 0"
    departure_pattern: uniform
    start_time_hour: 8.0

  - name: "test_env_2"
    num_vehicles: 300
    private_traffic_seed: 101
    public_traffic_seed: 201
    routing_strategy: "shortest 100"
    vehicle_types: "passenger 100"
    departure_pattern: uniform
    start_time_hour: 8.0
